CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	POST_READ_COUNT NUMBER DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_POST_MEMBERS FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_POST;
SELECT COUNT(*) FROM TBL_POST;

INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID)
(SELECT SEQ_POST.NEXTVAL, POST_TITLE, POST_CONTENT, MEMBER_ID FROM TBL_POST);


SELECT ID, POST_TITLE, POST_CONTENT, MEMBER_ID, CREATED_DATE, UPDATED_DATE, MEMBER_NAME
		FROM (
		SELECT ROWNUM R, P.ID, P.POST_TITLE, P.POST_CONTENT, P.MEMBER_ID, P.CREATED_DATE, P.UPDATED_DATE, M.MEMBER_NAME 
		FROM TBL_MEMBER M JOIN TBL_POST P
		ON M.ID = P.MEMBER_ID 
		WHERE ROWNUM <= 20 AND P.POST_TITLE LIKE '%q%'
		ORDER BY ID DESC
		)
		WHERE R >= 10;
