/*업종 대카테고리*/

CREATE SEQUENCE SEQ_CATEGORY_A;
CREATE TABLE TBL_CATEGORY_A(
	ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
	CATEGORY_A_NAME VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*업종 중카테고리*/
CREATE SEQUENCE SEQ_CATEGORY_B;
CREATE TABLE TBL_CATEGORY_B(
	ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
	CATEGORY_B_NAME VARCHAR2(1000) NOT NULL,
	CATEGORY_A_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_CATEGORY_B_A FOREIGN KEY(CATEGORY_A_ID)
	REFERENCES TBL_CATEGORY_A(ID)
);

/*업종 소카테고리*/
CREATE SEQUENCE SEQ_CATEGORY_C;
CREATE TABLE TBL_CATEGORY_C(
	ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
	CATEGORY_C_NAME VARCHAR2(1000) NOT NULL,
	CATEGORY_B_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_CATEGORY_C_B FOREIGN KEY(CATEGORY_B_ID)
	REFERENCES TBL_CATEGORY_B(ID)
	);


/*개인회원 테이블*/
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE VARCHAR2(1000) NOT NULL,
	MEMBER_REGISTER_DATE DATE DEFAULT SYSDATE,
	MEMBER_RECENT_LOGIN DATE DEFAULT SYSDATE,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PROFILE_PATH VARCHAR2(1000) NOT NULL,
	MEMBER_CLASS VARCHAR2(1000) DEFAULT '일반',
	MEMBER_POINT NUMBER(10) DEFAULT 0,
	MEMBER_STATUS VARCHAR(1000) DEFAULT '활성',
	MEMBER_BIRTH DATE DEFAULT SYSDATE,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

/*포트폴리오 테이블*/
CREATE SEQUENCE SEQ_MEMBER_PORTFOLIO;
CREATE TABLE TBL_MEMBER_PORTFOLIO(
	ID NUMBER CONSTRAINT PK_MEMBER_PORTFOLIO PRIMARY KEY,
	MEMBER_PORTFOLIO_NAME VARCHAR2(1000),
	MEMBER_PORTFOLIO_DATE DATE DEFAULT SYSDATE,
	MEMBER_PORTFOLIO_PATH VARCHAR2(1000),
	MEMBER_PORTFOLIO_TYPE VARCHAR2(1000) NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_MEMBER_PORTFOLIO_MEMBER FOREIGN KEY(MEMBER_ID) 
	REFERENCES TBL_MEMBER(ID)
);

/*기업회원 테이블*/
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(1000) NOT NULL,
	COMPANY_BUSINESS_NUMBER NUMBER NOT NULL,
	COMPANY_CEO VARCHAR2(1000),
	COMPANY_ESTABLISHMENT DATE NOT NULL,
	COMPANY_EMPLOYEE NUMBER NOT NULL,
	COMPANY_ADDRESS VARCHAR2(1000) NOT NULL,
	COMPANY_LOGO_PATH VARCHAR2(1000),
	COMPANY_URL VARCHAR(1000),
	COMPANY_CERTIFICATE_PATH VARCHAR(1000) NOT NULL,
	COMPANY_INTRODUCE VARCHAR2(1000),
	COMPANY_WELFARE VARCHAR2(1000),
	COMPANY_CULTURE VARCHAR2(1000),
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);



CREATE SEQUENCE SEQ_COMPANY_CATEGORY;
CREATE TABLE TBL_COMPANY_CATEGORY(
	ID NUMBER CONSTRAINT PK_COMPANY_CATEGORY PRIMARY KEY,
	COMPANY_ID NUMBER NOT NULL,
	CATEGORY_C_ID NUMBER NOT NULL,
	CONSTRAINT FK_COMPANY_CATEGORY_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
		CONSTRAINT FK_COMPANY_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
	REFERENCES TBL_CATEGORY_C(ID)
);

CREATE SEQUENCE SEQ_COMPANY_IMAGE;
CREATE TABLE TBL_COMPANY_IMAGE (
     ID NUMBER CONSTRAINT PK_COMPANY_IMAGE PRIMARY KEY,
     COMPANY_IMAGE_PATH VARCHAR2(1000),
     COMPANY_IMAGE_THUMBNAIL VARCHAR2(1000),
     COMPANY_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
	 UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT COMPANY_IMAGE_COMPANY FOREIGN KEY(COMPANY_ID)
     REFERENCES TBL_COMPANY(ID)
 );


CREATE SEQUENCE SEQ_MEMBER_CHARGE;
CREATE TABLE TBL_MEMBER_CHARGE(
	ID NUMBER CONSTRAINT PK_MEMBER_CHARGE PRIMARY KEY,
	MEMBER_ID NOT NULL,
	CHARGE NUMBER DEFAULT 0,
	PAYMENT_STATUS_LOACALE VARCHAR2(1000),
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT MEMBER_CHARGE_MEMBER FOREIGN KEY(MEMBER_ID)
     REFERENCES TBL_MEMBER(ID)
)
/*기업 담당자 테이블*/

CREATE SEQUENCE SEQ_COMPANY_MEMBER;
CREATE TABLE TBL_COMPANY_MEMBER(
	MEMBER_ID NUMBER PRIMARY KEY,
	COMPANY_ID NUMBER NOT NULL,
	COMPANY_MEMBER_POSITION VARCHAR2(1000) DEFAULT '사원',
	COMPANY_MEMBER_DEPARTMENT VARCHAR2(1000),
	COMPANY_MEMBER_AUTHORITY VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_COMPANY_MEMBER_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_COMPANY_MEMBER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

/*체험 프로그램 테이블*/
CREATE SEQUENCE SEQ_PROGRAM;
CREATE TABLE TBL_PROGRAM(
	ID NUMBER CONSTRAINT PK_PROGRAM PRIMARY KEY,
	PROGRAM_NAME VARCHAR2(1000) NOT NULL,
	PROGRAM_DETAIL VARCHAR2(1000) NOT NULL,
	PROGRAM_EXPIRED VARCHAR2(1000) DEFAULT '진행중',
	PROGRAM_STATUS VARCHAR2(1000) DEFAULT '심사중',
	PROGRAM_END_DATE DATE NOT NULL,
	PROGRAM_PRICE NUMBER NOT NULL,
	PROGRAM_BENEFIT VARCHAR2(1000) NOT NULL,
	PROGRAM_THUMBNAIL_PATH VARCHAR2(1000) NOT NULL,
	COMPANY_ID NUMBER NOT NULL,
	CATEGORY_C_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_PROGRAM_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_PROGRAM_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
	REFERENCES TBL_CATEGORY_C(ID)
);

/*스크랩 기능(공고랑 유저필요)*/
CREATE SEQUENCE SEQ_SCRAP;
CREATE TABLE TBL_SCRAP(
	ID NUMBER CONSTRAINT PK_SCRAP PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PROGRAM_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_SCRAP_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_SCRAP_PROGRAM FOREIGN KEY(PROGRAM_ID)
	REFERENCES TBL_PROGRAM(ID)
);

/*개인문의 테이블*/
CREATE SEQUENCE SEQ_MEMBER_INQUIRY;
CREATE TABLE TBL_MEMBER_INQUIRY(
	ID NUMBER CONSTRAINT PK_MEMBER_INQUIRY PRIMARY KEY,
	MEMBER_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	MEMBER_INQUIRY_DETAIL VARCHAR2(1000),
	MEMBER_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

/*기업문의 테이블*/
CREATE SEQUENCE SEQ_COMPANY_INQUIRY;
CREATE TABLE TBL_COMPANY_INQUIRY(
	ID NUMBER CONSTRAINT PK_COMPANY_INQUIRY PRIMARY KEY,
	COMPANY_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	COMPANY_INQUIRY_DETAIL VARCHAR2(1000),
	COMPANY_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_INQUIRY_COMPANY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_COMPANY_MEMBER(MEMBER_ID)
);

/*문의 답변 테이블*/
CREATE SEQUENCE SEQ_INQUIRY_ANSWER;
CREATE TABLE TBL_INQUIRY_ANSWER(
	ID NUMBER CONSTRAINT PK_INQUIRY_ANSWER PRIMARY KEY,
	INQUIRY_ANSWER_TITLE VARCHAR2(1000) NOT NULL,
	INQUIRY_ANSWER_DETAIL VARCHAR2(1000),
	MEMBER_INQUIRY_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_INQUIRY_ANSWER_MEMBER FOREIGN KEY(MEMBER_INQUIRY_ID)
	REFERENCES TBL_MEMBER_INQUIRY(ID)
);

CREATE SEQUENCE SEQ_COMPANY_INQUIRY_ANSWER;
CREATE TABLE TBL_COMPANY_INQUIRY_ANSWER(
	ID NUMBER CONSTRAINT PK_COMPANY_INQUIRY_ANSWER PRIMARY KEY,
	INQUIRY_ANSWER_TITLE VARCHAR2(1000) NOT NULL,
	INQUIRY_ANSWER_DETAIL VARCHAR2(1000),
	COMPANY_INQUIRY_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_INQUIRY_ANSWER_COMPANY FOREIGN KEY(COMPANY_INQUIRY_ID)
	REFERENCES TBL_COMPANY_INQUIRY(ID)
);

CREATE SEQUENCE SEQ_RESUME_IMAGE;
CREATE TABLE TBL_RESUME_IMAGE(
	 ID NUMBER CONSTRAINT PK_RESUME_IMAGE PRIMARY KEY,
     RESUME_IMAGE_PATH VARCHAR2(1000),
     RESUME_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
	 UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT RESUME_IMAGE_RESUME FOREIGN KEY(RESUME_ID)
     REFERENCES TBL_RESUME(ID)
);

/*신고 테이블*/
CREATE SEQUENCE SEQ_REPORT;
CREATE TABLE TBL_REPORT(
	ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
	REPORT_DATE DATE DEFAULT SYSDATE,
	REPORT_SUBJECT VARCHAR2(1000) NOT NULL,
	REPORT_TYPE VARCHAR2(1000) NOT NULL,
	REPORT_DETAIL VARCHAR2(1000),
	REPORT_STATUS VARCHAR2(1000) DEFAULT '처리중',
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);


/*신고 답변 테이블*/
CREATE SEQUENCE SEQ_REPORT_ANSWER;
CREATE TABLE TBL_REPORT_ANSWER(
	ID NUMBER CONSTRAINT PK_REPORT_ANSWER PRIMARY KEY,
	REPORT_ANSWER_TITLE VARCHAR2(1000) NOT NULL,
	REPORT_ANSWER_DETAIL VARCHAR2(1000),
	REPORT_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_REPORT_ANSWER FOREIGN KEY(REPORT_ID)
	REFERENCES TBL_REPORT(ID)
);

/*공지사항 테이블*/
CREATE SEQUENCE SEQ_NOTICE;
CREATE TABLE TBL_NOTICE(
	ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	NOTICE_CATEGORY VARCHAR2(1000),
	NOTICE_TITLE VARCHAR2(1000) NOT NULL,
	NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_ADMIN;
CREATE TABLE TBL_ADMIN(
	ID NUMBER CONSTRAINT PK_ADMIN PRIMARY KEY,
	ADMIN_ID VARCHAR2(1000) NOT NULL,
	ADMIN_PASSWORD VARCHAR2(1000) NOT NULL
);


/* 개인회원 이력서*/
CREATE SEQUENCE SEQ_RESUME;
CREATE TABLE TBL_RESUME(
    ID NUMBER CONSTRAINT PK_RESUME PRIMARY KEY,
    RESUME_TITLE VARCHAR2(1000),
    RESUME_PROFILE_PHOTO VARCHAR2(1000),
    RESUME_INTRODUCE VARCHAR2(1000),
    MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RESUME_MEMBER FOREIGN KEY(MEMBER_ID)
     REFERENCES TBL_MEMBER(ID)
);


/* 지원 현황 */
CREATE SEQUENCE SEQ_APPLY;
CREATE TABLE TBL_APPLY(
	ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
	APPLY_MEMBER_STATUS VARCHAR2(1000) DEFAULT '지원 완료',
	APPLY_COMPANY_STATUS VARCHAR2(1000) DEFAULT '지원 완료',
	MEMBER_ID NUMBER NOT NULL,
	PROGRAM_ID NUMBER NOT NULL,
	RESUME_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_APPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_APPLY_RESUME FOREIGN KEY(RESUME_ID)
	REFERENCES TBL_RESUME(ID)
	CONSTRAINT FK_APPLY_PROGRAM FOREIGN KEY(PROGRAM_ID)
	REFERENCES TBL_PROGRAM(ID)
);

CREATE SEQUENCE SEQ_APPLICANT_EVALUATION;
CREATE TABLE TBL_APPLICANT_EVALUATION(
	ID NUMBER CONSTRAINT PK_APPLICANT_EVALUATION PRIMARY KEY,
	APPLICANT_EVALUATION_CONTENT VARCHAR2(1000),
	APPLICANT_EVALUATION_RATING VARCHAR2(1000),
	MEMBER_ID NUMBER NOT NULL,
	PROGRAM_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_EVALUATION_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_EVALUATION_PROGRAM FOREIGN KEY(PROGRAM_ID)
	REFERENCES TBL_PROGRAM(ID)
);

CREATE SEQUENCE SEQ_PAYMENT;
CREATE TABLE TBL_PAYMENT(
	ID NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PROGRAM_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_PAYMENT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_PAYMENT_PROGRAM FOREIGN KEY(PROGRAM_ID)
	REFERENCES TBL_PROGRAM(ID)
);
	

SELECT * FROM TBL_CATEGORY_A;
INSERT INTO  TBL_CATEGORY_A(ID, CATEGORY_A_NAME, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_CATEGORY_A.NEXTVAL, 'IT', SYSDATE, SYSDATE);

SELECT * FROM TBL_CATEGORY_B;
INSERT INTO TBL_CATEGORY_B(ID, CATEGORY_B_NAME, CATEGORY_A_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_CATEGORY_B.NEXTVAL,'WEB', 1, SYSDATE, SYSDATE);

SELECT * FROM TBL_CATEGORY_C;
INSERT INTO TBL_CATEGORY_C(ID, CATEGORY_C_NAME, CATEGORY_B_ID, CREATED_DATE, UPDATED_DATE)
VALUES (SEQ_CATEGORY_C.NEXTVAL, 'BACKEND', 1, SYSDATE, SYSDATE);


INSERT INTO TBL_PROGRAM(ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS ,PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_PROGRAM.NEXTVAL, '풀스택 융합','프론트엔드와 백엔드를 어우르는 것', '진행 중', '승인완료',
       '2025-03-01', 10000, '인턴 전환', 'TEMP',1,1, SYSDATE, SYSDATE);
      
      
      INSERT INTO TBL_APPLY(ID, APPLY_MEMBER_STATUS, APPLY_COMPANY_STATUS, MEMBER_ID, PROGRAM_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_APPLY.NEXTVAL,'지원 완료','지원 완료',1,1, SYSDATE, SYSDATE);


INSERT INTO TBL_REPORT(ID,REPORT_DATE,REPORT_SUBJECT,REPORT_TYPE,REPORT_DETAIL ,REPORT_STATUS,MEMBER_ID,CREATED_DATE,UPDATED_DATE)
VALUES(SEQ_REPORT.NEXTVAL, SYSDATE, '코리아IT아카데미', '스팸','허위 프로그램', '처리완료',2,SYSDATE, SYSDATE);

INSERT INTO TBL_COMPANY_MEMBER(MEMBER_ID, COMPANY_ID, COMPANY_MEMBER_POSITION, COMPANY_MEMBER_AUTHORITY, CREATED_DATE,UPDATED_DATE)
VALUES(2,1,'사원','뷰어',SYSDATE,SYSDATE);

INSERT INTO TBL_RESUME(ID, RESUME_TITLE, RESUME_PROFILE_PHOTO, RESUME_INTRODUCE, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_RESUME.NEXTVAL, '최고의 천재','O:\FileHistory', '천재입니다.',5,SYSDATE,SYSDATE);
      

INSERT INTO TBL_COMPANY_INQUIRY(ID, COMPANY_INQUIRY_TYPE, COMPANY_INQUIRY_DETAIL, COMPANY_INQUIRY_STATUS, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_COMPANY_INQUIRY.NEXTVAL,'기타','멤버 초대 오류','보류중',1,SYSDATE,SYSDATE);

SELECT * FROM TBL_MEMBER;