--CREATE TABLE TBL_MEMBER(
--	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
--	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
--   	MEMBER_EMAIL VARCHAR2(255) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
--	MEMBER_NAME VARCHAR2(255) NOT NULL,
--   	MEMBER_PHONE VARCHAR2(255) NOT NULL,
--   	MEMBER_BIRTH DATE,
--   	MEMBER_STATUS VARCHAR2(255) DEFAULT '일반'
--   	
--);
--/* 기업회원으로 체크하고 가입하는 경우에는, 기업담당자 DB에 연결되어야 함.*/
--/**/
--CREATE TABLE TBL_COMPANY_MANAGER(
--	ID NUMBER CONSTRAINT PK_COMPANY_MANAGER PRIMARY KEY,
--	COMPANY_MANAGER_AUTHORITY VARCHAR2(255) DEFAULT '뷰어',
--	COMPANY_MANAGER
--	
--	COMPANY_ID NUMBER,
--); 


/*업종 대카테고리*/
CREATE SEQUENCE SEQ_CATEGORY_A;
CREATE TABLE TBL_CATEGORY_A(
	ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
	CATEGORY_A_NAME VARCHAR2(1000) NOT NULL
);

/*업종 중카테고리*/
CREATE SEQUENCE SEQ_CATEGORY_B;
CREATE TABLE TBL_CATEGORY_B(
	ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
	CATEGORY_B_NAME VARCHAR2(1000) NOT NULL,
	CATEGORY_A_ID NUMBER NOT NULL,
	CONSTRAINT FK_CATEGORY_B_A FOREIGN KEY(CATEGORY_A_ID)
	REFERENCES TBL_CATEGORY_A(ID)
);

/*업종 소카테고리*/
CREATE SEQUENCE SEQ_CATEGORY_C;
CREATE TABLE TBL_CATEGORY_C(
	ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
	CATEGORY_C_NAME VARCHAR2(1000) NOT NULL,
	CATEGORY_B_ID NUMBER NOT NULL,
	CONSTRAINT FK_CATEGORY_C_B FOREIGN KEY(CATEGORY_B_ID)
	REFERENCES TBL_CATEGORY_B(ID)
);

/*개인회원 테이블*/
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE VARCHAR2(1000) NOT NULL,
	MEMBER_REGISTER_DATE DATE DEFAULT SYSDATE,
	MEMBER_RECENT_LOGIN DATE DEFAULT SYSDATE,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PROFILE_PATH VARCHAR2(1000) NOT NULL,
	MEMBER_INTRODUCE VARCHAR2(1000),
	MEMBER_EDUCATION VARCHAR2(1000),
	MEMBER_EXTRA VARCHAR2(1000)
);

CREATE TABLE TBL_MEMBER_EDUCATION(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EDUCATION_DEGREE VARCHAR2(255) NOT NULL,
	MEMBER_EDUCATION_NAME VARCHAR2(255) NOT NULL,
	MEMBER_EDUCATION_MAJOR VARCHAR2(255),
	MEMBER_EDUCATION_GRADE NUMBER(2,1),
	MEMBER_ID NUMBER,
	CONSTRAINT FK_MEMBER_EDU_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER_ID
);

CREATE TABLE TBL_MEMBER_CAREER(
	ID NUMBER CONSTRAINT PK_CAREER PRIMARY KEY,
	MEMBER_CAREER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_CAREER_POSITION VARCHAR2(255) NOT NULL,
	MEMBER_CAREER_DETAIL VARCHAR2(255) NOT NULL,
	MEMBER_CAREER_STARTDATE DATE,
	MEMBER_CAREER_ENDDATE DATE,
	MEMBER_CAREER_STATUS VARCHAR2(255) NOT NULL
/* 재직 중 OR 퇴직 */




/*기업회원 테이블*/
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_BUSINESS_NUMBER NUMBER NOT NULL,
	COMPANY_CEO VARCHAR2(1000) NOT NULL,
	COMPANY_ESTABLISHMENT DATE NOT NULL,
	COMPANY_SORT VARCHAR2(1000) NOT NULL,
	COMPANY_EMPLOYEE NUMBER NOT NULL,
	COMPANY_ADDRESS VARCHAR2(1000) NOT NULL,
	COMPANY_LOGO_PATH VARCHAR2(1000) NOT NULL,
	COMPANY_CERTIFICATE_PATH VARCHAR(1000) NOT NULL,
	COMPANY_INTRODUCE VARCHAR2(1000),
	COMPANY_FINANCE VARCHAR2(1000),
	COMPANY_WELFARE VARCHAR2(1000),
	COMPANY_CULTURE VARCHAR2(1000),
	COMPANY_EXTRA_INFO VARCHAR2(1000),
	CATEGORY_C_ID NUMBER NOT NULL,
	CONSTRAINT FK_COMPANY_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
	REFERENCES TBL_CATEGORY_C(ID)
);

/*기업 담당자 테이블*/
CREATE SEQUENCE SEQ_COMPANY_MANAGER;
CREATE TABLE TBL_COMPANY_MANAGER(
	ID NUMBER CONSTRAINT PK_COMPANY_MANAGER PRIMARY KEY,
	COMPANY_MANAGER_NAME VARCHAR2(1000) NOT NULL,
	COMPANY_MANAGER_POSITION VARCHAR2(1000),
	COMPANY_MANAGER_ID VARCHAR2(1000) NOT NULL,
	COMPANY_MANAGER_PHONE VARCHAR2(1000) NOT NULL,
	COMPANY_MANAGER_REGISTER_DATE DATE DEFAULT SYSDATE,
	COMPANY_MANAGER_RECENT_LOGIN DATE DEFAULT SYSDATE,
	COMPANY_MANAGER_EMAIL VARCHAR2(1000) NOT NULL,
	COMPANY_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_COMPANY_MANAGER_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_COMPANY_MANAGER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

/*체험 프로그램 테이블*/
CREATE SEQUENCE SEQ_PROGRAM;
CREATE TABLE TBL_PROGRAM(
	ID NUMBER CONSTRAINT PK_PROGRAM PRIMARY KEY,
	PROGRAM_NAME VARCHAR2(1000) NOT NULL,
	PROGRAM_END_DATE VARCHAR2(1000) NOT NULL,
	PROGRAM_PRICE NUMBER NOT NULL,
	PROGRAM_THUMBNAIL_PATH VARCHAR2(1000) NOT NULL,
	PROGRAM_CREATED_DATE DATE DEFAULT SYSDATE,
	PROGRAM_UPDATE_DATE DATE DEFAULT SYSDATE,
	COMPANY_ID NUMBER NOT NULL,
	CATEGORY_C_ID NUMBER NOT NULL,
	CONSTRAINT FK_PROGRAM_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_PROGRAM_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
	REFERENCES TBL_CATEGORY_C(ID)
);

/*스크랩 기능(공고랑 유저필요)*/
CREATE SEQUENCE SEQ_SCRAP;
CREATE TABLE TBL_SCRAP(
	ID NUMBER CONSTRAINT PK_SCRAP PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PROGRAM_ID NUMBER NOT NULL,
	CONSTRAINT FK_SCRAP_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_SCRAP_PROGRAM FOREIGN KEY(PROGRAM_ID)
	REFERENCES TBL_PROGRAM(ID)
);

/*개인문의 테이블*/
CREATE SEQUENCE SEQ_MEMBER_INQUIRY;
CREATE TABLE TBL_MEMBER_INQUIRY(
	ID NUMBER CONSTRAINT PK_MEMBER_INQUIRY PRIMARY KEY,
	MEMBER_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	MEMBER_INQUIRY_DETAIL VARCHAR2(1000),
	MEMBER_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	MEMBER_INQUIRY_ADMIN_MEMO VARCHAR2(1000),
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

/*기업문의 테이블*/
CREATE SEQUENCE SEQ_COMPANY_INQUIRY;
CREATE TABLE TBL_COMPANY_INQUIRY(
	ID NUMBER CONSTRAINT PK_COMPANY_INQUIRY PRIMARY KEY,
	COMPANY_INQUIRY_TYPE VARCHAR2(1000) NOT NULL,
	COMPANY_INQUIRY_DETAIL VARCHAR2(1000),
	COMPANY_INQUIRY_STATUS VARCHAR2(1000) DEFAULT '처리중',
	COMPANY_INQUIRY_ADMIN_MEMO VARCHAR2(1000),
	COMPANY_MANAGER_ID NUMBER NOT NULL,
	CONSTRAINT FK_INQUIRY_COMPANY_MANAGER FOREIGN KEY(COMPANY_MANAGER_ID)
	REFERENCES TBL_COMPANY_MANAGER(ID)
);

/*문의 답변 테이블*/
CREATE SEQUENCE SEQ_INQUIRY_ANSWER;
CREATE TABLE TBL_INQUIRY_ANSWER(
	ID NUMBER CONSTRAINT PK_INQUIRY_ANSWER PRIMARY KEY,
	INQUIRY_ANSWER_TITLE VARCHAR2(1000) NOT NULL,
	INQUIRY_ANSWER_DETAIL VARCHAR2(1000),
	COMPANY_INQUIRY_ID NUMBER NOT NULL,
	MEMBER_INQUIRY_ID NUMBER NOT NULL,
	CONSTRAINT FK_INQUIRY_ANSWER_COMPANY FOREIGN KEY(COMPANY_INQUIRY_ID)
	REFERENCES TBL_COMPANY_INQUIRY(ID),
	CONSTRAINT FK_INQUIRY_ANSWER_MEMBER FOREIGN KEY(MEMBER_INQUIRY_ID)
	REFERENCES TBL_MEMBER_INQUIRY(ID)
);

/*신고 테이블*/
CREATE SEQUENCE SEQ_REPORT;
CREATE TABLE TBL_REPORT(
	ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
	REPORT_DATE DATE DEFAULT SYSDATE,
	REPORT_REPORTER VARCHAR2(1000) NOT NULL,
	REPORT_SUBJECT VARCHAR2(1000) NOT NULL,
	REPORT_TYPE VARCHAR2(1000) NOT NULL,
	REPORT_DETAIL VARCHAR2(1000),
	REPORT_STATUS VARCHAR2(1000) DEFAULT '처리중',
	REPORT_ADMIN_MEMO VARCHAR2(1000),
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

/*신고 답변 테이블*/
CREATE SEQUENCE SEQ_REPORT_ANSWER;
CREATE TABLE TBL_REPORT_ANSWER(
	ID NUMBER CONSTRAINT PK_REPORT_ANSWER PRIMARY KEY,
	REPORT_ANSWER_TITLE VARCHAR2(1000) NOT NULL,
	REPORT_ANSWER_DETAIL VARCHAR2(1000),
	REPORT_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPORT_ANSWER FOREIGN KEY(REPORT_ID)
	REFERENCES TBL_REPORT(ID)
);

/*공지사항 테이블*/
CREATE SEQUENCE SEQ_NOTICE;
CREATE TABLE TBL_NOTICE(
	ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	NOTICE_CATEGORY VARCHAR2(1000),
	NOTICE_TITLE VARCHAR2(1000) NOT NULL,
	NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
	NOTICE_CREATE_DATE DATE DEFAULT SYSDATE,
	NOTICE_UPDATE_DATE DATE DEFAULT SYSDATE
);


CREATE TABLE TBL_EDUCATION(
	ID NUMBER CONSTRAINT PK_EDUCATION PRIMARY KEY,
	
);